[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "matrix-factorization-pytorch"
version = "0.1.0"
description = "Matrix Factorization Recommender Models in PyTorch with MovieLens"
authors = ["YuXuan Tay <wyextay@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flaml = "^2.1.2"
lightning = "^2.2.1"
loguru = "^0.7.2"
mlflow = "^2.12.1"
mmh3 = "^4.1.0"
optuna = "^3.6.1"
polars = { extras = ["pandas"], version = "^0.20.19" }
ray = { extras = ["data", "train", "tune"], version = "^2.10.0" }
rich = "^13.7.0"
tensorboard = "^2.16.2"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.1"
ruff = "^0.2.1"
