[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "matrix-factorization-pytorch"
version = "0.1.0"
description = "Matrix Factorization Recommender Models in PyTorch with MovieLens"
authors = ["YuXuan Tay <wyextay@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flaml = "^2.1.2"
lightning = "^2.2.0"
loguru = "^0.7.2"
mlflow = "^2.11.2"
mmh3 = "^4.1.0"
optuna = "^3.5.0"
pandas = "~=2.1.4"
polars = "^0.20.10"
ray = { extras = ["data", "train", "tune"], version = "^2.9.3" }
requests = "^2.31.0"
rich = "^13.7.0"
tensorboard = "^2.6.2"
torch = "^2.2.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.1"
ruff = "^0.2.1"
